---
- name: Ensure NGINX is installed
  yum:
    name: nginx-1.20.1
    state: present

- name: Prepare web server service switch
  import_role:
    name: webserver_switch

- name: Ensure NGINX is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Configure firewall for NGINX
  import_role:
    name: firewall

- name: Copy the meme to the NGINX HTML directory
  copy:
    src: ../files/meme.png
    dest: /usr/share/nginx/html/meme.png

- name: Create a custom index page, using a template for dynamic content, for all hosts but dev
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    force: yes
