---
- name: Configure Web Servers
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure the yum package index is up to date
      yum:
        update_cache: yes
  
    - name: Ensure NGINX is installed
      yum:
        name: nginx-1.20.1
        state: present

    - name: Ensure NGINX is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: true
  
    - name: Ensure firewalld is installed and enabled
      package:
        name: firewalld
        state: present

    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Open HTTP and HTTPS ports for apache
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - http
        - https

    - name: Reload firewalld to apply changes
      service:
        name: firewalld
        state: reloaded
  
    - name: Copy the current meme image to the NGINX HTML directory
      copy:
        src: ./meme.png
        dest: /usr/share/nginx/html/meme.png

    - name: Create a custom index page, using a template for dynamic content, for all hosts but dev
      template:
        src: ./index.html.j2
        dest: /usr/share/nginx/html/index.html
        force: yes
